/* ================================================================
   SUDOKU · COACH — leçons de l'onglet « Apprendre »
   Chaque leçon est une position vérifiée illustrant une technique :
   - given    : valeurs affichées {index: chiffre}
   - notes    : candidats affichés {index: [chiffres]}
   - removals : candidats barrés à la révélation {index: [chiffres]}
   - unit     : cases teintées (zone étudiée)
   - focus    : cases encadrées (cases clés de la technique)
   - target   : case résolue, answer : chiffre trouvé
   Pas à pas (optionnel, partagé fr/en — parallèle à steps) :
   - stepCells   : [[index, ...], ...] cases surlignées à l'étape i
   - stepStrikes : [{index: [chiffres]}, ...] candidats barrés PAR l'étape i
     (l'union des stepStrikes == removals ; absents → révélation d'un bloc)
   ================================================================ */
import { ROWS, COLS, BOXES } from "./engine.js";
import { LESSONS_EN } from "./lessonsEn.js";

export const LESSONS = [
  {
    id: "naked-single",
    num: 1,
    level: "classic",
    title: "Candidat unique",
    concept:
      "Chaque case vide a des chiffres possibles : on les appelle ses [[candidats]]. Quand une case n’en garde qu’un seul, ce chiffre est forcément le bon. C’est le [[candidat unique]] — la technique de base, à toujours essayer d’abord.",
    question: "Quel chiffre va dans la case L5C5 ?",
    hint: "Écris les chiffres 1 à 9 sur un papier. [[Barre]] chaque chiffre que la case L5C5 [[voit]] dans sa [[ligne]], sa [[colonne]] et son [[bloc]]. Que reste-t-il ?",
    given: { 36: 1, 37: 2, 44: 3, 4: 4, 13: 5, 30: 6, 50: 8, 32: 9 },
    notes: {},
    removals: {},
    unit: [...ROWS[4], ...COLS[4], ...BOXES[4]],
    focus: [],
    target: 40,
    answer: 7,
    steps: [
      "Regarde la case **L5C5**. Sa [[ligne]] contient déjà 1, 2 et 3. Sa [[colonne]] contient 4 et 5, et son [[bloc]] contient 6, 8 et 9.",
      "[[Barre]] ces huit chiffres dans la case : 1, 2, 3, 4, 5, 6, 8 et 9 sont impossibles.",
      "Il ne reste qu’un seul [[candidat]] : le **7**. Écris donc **7** dans la case **L5C5**.",
    ],
    stepCells: [[40], [40], [40]],
    stepStrikes: [{}, {}, {}],
  },
  {
    id: "hidden-single",
    num: 2,
    level: "classic",
    title: "Single caché",
    concept:
      "Suis un seul chiffre dans une [[zone]] : s’il n’a plus qu’une place possible, il s’y pose. C’est le [[single caché]]. La case peut avoir d’autres [[candidats]] : peu importe, ce chiffre n’a nulle part ailleurs où aller.",
    question: "Où va le 5 dans le bloc haut-gauche ?",
    hint: "Suis le 5. Quelles cases libres du bloc sont [[vues]] par un 5 déjà posé, sur la même ligne ou la même colonne ?",
    given: { 0: 2, 1: 9, 10: 7, 20: 4, 6: 5, 13: 5, 45: 5 },
    notes: {},
    removals: {},
    unit: BOXES[0],
    focus: [6, 13, 45],
    target: 19,
    answer: 5,
    steps: [
      "Cherche où placer le **5** dans le bloc haut-gauche. Ses cases libres sont L1C3, L2C1, L2C3, L3C1 et L3C2.",
      "Regarde le 5 de **L1C7** : il occupe déjà la ligne 1, donc **L1C3** est impossible. Le 5 de **L2C5** occupe la ligne 2 : **L2C1** et **L2C3** sont impossibles.",
      "Regarde le 5 de **L6C1** : il occupe déjà la colonne 1, donc **L3C1** est impossible.",
      "Il ne reste que **L3C2** : elle ne [[voit]] aucun 5. Écris donc **5** dans **L3C2**.",
    ],
    stepCells: [[2, 9, 11, 18, 19], [2, 6, 9, 11, 13], [18, 45], [19]],
    stepStrikes: [{}, {}, {}, {}],
  },
  {
    id: "naked-pair",
    num: 3,
    level: "classic",
    title: "Paire nue",
    concept:
      "Deux cases d’une même [[zone]] n’acceptent que les deux mêmes chiffres : c’est une [[paire nue]]. Ces deux chiffres sont réservés à ces deux cases, dans un ordre ou l’autre. Tu peux donc les [[barrer]] partout ailleurs dans la zone.",
    question: "La paire 3 et 8 de la ligne 4 débloque une case. Laquelle, et avec quel chiffre ?",
    hint: "Repère les deux cases de la ligne 4 qui partagent exactement les mêmes deux [[candidats]]. Puis barre ces chiffres ailleurs dans la ligne.",
    given: { 29: 1, 31: 2, 35: 9 },
    notes: {
      27: [3, 8], 28: [3, 8], 30: [4, 5, 8],
      32: [3, 5, 7], 33: [3, 6, 8], 34: [4, 6, 7],
    },
    removals: { 30: [8], 32: [3], 33: [3, 8] },
    unit: ROWS[3],
    focus: [27, 28],
    target: 33,
    answer: 6,
    steps: [
      "Regarde **L4C1** et **L4C2** : chacune n’accepte que 3 et 8. Le 3 et le 8 de la ligne 4 iront forcément dans ces deux cases. C’est une [[paire nue]].",
      "Aucune autre case de la ligne 4 ne peut donc être un 3 ou un 8. Barre le 8 de **L4C4**, le 3 de **L4C6**, et le 3 et le 8 de **L4C7**.",
      "Dans **L4C7**, il ne reste plus que le **6**. Écris donc **6** dans **L4C7** : la paire nue a fabriqué un [[candidat unique]].",
    ],
    stepCells: [[27, 28], [27, 28, 30, 32, 33], [33]],
    stepStrikes: [{}, { 30: [8], 32: [3], 33: [3, 8] }, {}],
  },
  {
    id: "pointing-pair",
    num: 4,
    level: "classic",
    title: "Paire pointante",
    concept:
      "Dans un [[bloc]], un chiffre n’a parfois ses places restantes que sur une seule [[ligne]]. Ce chiffre finira forcément dans le bloc, sur cette ligne. Tu peux donc le [[barrer]] sur le reste de la ligne, hors du bloc. C’est la [[paire pointante]].",
    question: "Suis les 4 du bloc haut-droit. Quel chiffre va dans la case L2C4 ?",
    hint: "Cherche les cases du bloc haut-droit qui peuvent encore recevoir un 4. Regarde comment elles s’alignent.",
    given: { 6: 9, 7: 1, 25: 6 },
    notes: {
      16: [4, 5], 17: [4, 8], 8: [3, 7], 24: [2, 5], 26: [2, 3],
      10: [3, 4, 6], 12: [4, 7],
    },
    removals: { 10: [4], 12: [4] },
    unit: [...BOXES[2], ...ROWS[1]],
    focus: [16, 17],
    target: 12,
    answer: 7,
    steps: [
      "Suis le **4** dans le bloc haut-droit. Il n’a plus que deux places : **L2C7** et **L2C9**, toutes les deux sur la [[ligne]] 2. C’est une [[paire pointante]].",
      "Le 4 du bloc sera donc **L2C7** ou **L2C9**. Aucune autre case de la ligne 2 ne peut être un 4. [[Barre]] le 4 de **L2C2** et de **L2C4**.",
      "Dans la case **L2C4**, il ne reste plus que le **7**. Écris donc **7** dans **L2C4**.",
    ],
    stepCells: [[16, 17], [10, 12, 16, 17], [12]],
    stepStrikes: [{}, { 10: [4], 12: [4] }, {}],
  },
  {
    id: "claiming",
    num: 5,
    level: "classic",
    title: "Réduction bloc/ligne",
    concept:
      "Sur une [[ligne]] ou une [[colonne]], un chiffre n’a parfois ses places restantes que dans un seul [[bloc]]. Ce chiffre finira donc dans ce bloc, sur cette ligne. Tu peux le [[barrer]] des autres cases du bloc : c’est la [[réduction bloc/ligne]], la paire pointante à l’envers.",
    question: "Suis le 6 de la colonne 5. Quel chiffre va dans la case L5C4 ?",
    hint: "Dans la colonne 5, quelles cases peuvent encore recevoir un 6 ? Dans quel bloc tombent-elles toutes ?",
    given: { 4: 3, 58: 4, 76: 5 },
    notes: {
      13: [1, 8], 22: [1, 9], 31: [2, 6], 40: [6, 7], 49: [2, 7], 67: [8, 9],
      39: [5, 6], 32: [6, 8, 9],
    },
    removals: { 39: [6], 32: [6] },
    unit: [...COLS[4], ...BOXES[4]],
    focus: [31, 40],
    target: 39,
    answer: 5,
    steps: [
      "Suis le **6** dans la colonne 5 : il n’a plus que deux places, **L4C5** et **L5C5**. Toutes les deux sont dans le bloc central.",
      "Le 6 de la colonne 5 tombera donc dans le bloc central. Aucune autre case de ce bloc ne peut être un 6. Barre le 6 de **L5C4** et de **L4C6**.",
      "Dans la case **L5C4**, il ne reste plus que le **5**. Écris donc **5** dans **L5C4**.",
    ],
    stepCells: [[31, 40], [31, 32, 39, 40], [39]],
    stepStrikes: [{}, { 39: [6], 32: [6] }, {}],
  },
  {
    id: "hidden-pair",
    num: 6,
    level: "classic",
    title: "Duo caché",
    concept:
      "Deux chiffres n’ont chacun que deux places dans une [[zone]], et ce sont les deux mêmes cases : c’est un [[duo caché]]. Ces deux cases leur sont réservées. Tu peux [[barrer]] tous leurs autres [[candidats]], et ce nettoyage débloque souvent la suite.",
    question: "Trouve le duo caché du bloc bas-gauche. Quelle case se débloque ensuite ?",
    hint: "Passe les chiffres en revue un par un. Lesquels n’apparaissent que dans les deux mêmes cases du bloc ?",
    given: { 56: 3, 65: 7 },
    notes: {
      54: [1, 5], 55: [5, 6], 63: [4, 6], 64: [2, 4, 6, 9],
      72: [4, 5], 73: [4, 5, 6], 74: [1, 2, 5, 9],
    },
    removals: { 64: [4, 6], 74: [1, 5] },
    unit: BOXES[6],
    focus: [64, 74],
    target: 54,
    answer: 1,
    steps: [
      "Dans le bloc bas-gauche, suis le **2** puis le **9** : chacun n’apparaît que dans **L8C2** et **L9C3**. C’est un [[duo caché]].",
      "Ces deux cases sont réservées au 2 et au 9. Barre leurs autres candidats : le 4 et le 6 de **L8C2**, le 1 et le 5 de **L9C3**.",
      "Le **1** du bloc n’a plus qu’une seule place : **L7C1**. Écris donc **1** dans **L7C1** : le duo caché a débloqué un [[single caché]].",
    ],
    stepCells: [[64, 74], [64, 74], [54]],
    stepStrikes: [{}, { 64: [4, 6], 74: [1, 5] }, {}],
  },
  {
    id: "x-wing",
    num: 7,
    level: "intermediate",
    title: "X-Wing",
    concept:
      "Parfois un chiffre n’a plus que deux places sur chacune de deux [[lignes]], dans les deux mêmes [[colonnes]]. Ces quatre cases dessinent un rectangle : c’est le [[X-Wing]]. Le chiffre prendra un coin en haut et un coin en bas, un par colonne. Il est donc réservé à ces deux colonnes : [[barre]]-le partout ailleurs dans ces colonnes.",
    question: "Le 4 est bloqué sur les lignes 1 et 5. Quel chiffre se libère dans la case L3C2 ?",
    hint: "Suis le 4 sur la ligne 1, puis sur la ligne 5. Dans quelles colonnes tombe-t-il ? Regarde le rectangle.",
    given: {},
    notes: {
      1: [4, 8], 5: [4, 9], 37: [4, 6], 41: [4, 5],
      19: [4, 7], 68: [2, 4],
    },
    removals: { 19: [4], 68: [4] },
    unit: [...COLS[1], ...COLS[5]],
    focus: [1, 5, 37, 41],
    target: 19,
    answer: 7,
    steps: [
      "Suis le **4** sur la ligne 1 : il ne reste que **L1C2** et **L1C6**. Sur la ligne 5, il ne reste que **L5C2** et **L5C6**. Toutes ces places tombent dans les [[colonnes]] 2 et 6.",
      "Ces quatre cases dessinent un rectangle : un [[X-Wing]]. Chaque colonne prendra un 4 sur la ligne 1 ou la ligne 5. Aucune autre case des colonnes 2 et 6 ne peut être un 4 : [[barre]] le 4 de **L3C2** et de **L8C6**.",
      "Dans la case **L3C2**, il ne reste plus que le **7**. Écris donc **7** dans **L3C2**.",
    ],
    stepCells: [[1, 5, 37, 41], [1, 5, 19, 37, 41, 68], [19]],
    stepStrikes: [{}, { 19: [4], 68: [4] }, {}],
  },
  {
    id: "xy-wing",
    num: 8,
    level: "intermediate",
    title: "XY-Wing",
    concept:
      "Trois cases à deux [[candidats]] forment un Y : un [[pivot]] et deux [[pinces]] qu’il [[voit]]. Le pivot hésite entre a et b, une pince entre a et c, l’autre entre b et c. Quel que soit le pivot, une pince vaudra c : toute case qui voit les deux pinces perd le c. C’est le [[XY-Wing]].",
    question: "Le pivot L5C5 et ses deux pinces débloquent L1C1. Avec quel chiffre ?",
    hint: "Repère le pivot qui hésite entre 1 et 2. Ses deux pinces partagent un même troisième chiffre : lequel ?",
    given: {},
    notes: { 40: [1, 2], 36: [1, 3], 4: [2, 3], 0: [3, 7] },
    removals: { 0: [3] },
    unit: [0, 4, 36, 40],
    focus: [40, 36, 4],
    target: 0,
    answer: 7,
    steps: [
      "Le [[pivot]] **L5C5** hésite entre 1 et 2. Sa première [[pince]] **L5C1** hésite entre 1 et 3, sur la même ligne. Sa seconde pince **L1C5** hésite entre 2 et 3, sur la même colonne.",
      "Si L5C5 vaut 1, alors L5C1 vaut 3. Si L5C5 vaut 2, alors L1C5 vaut 3. Dans les deux cas, un 3 apparaît en **L5C1** ou en **L1C5**.",
      "**L1C1** voit ces deux pinces : elle ne peut pas être un 3. Barre le 3 de L1C1 : il ne reste que le **7**. Écris donc **7** dans **L1C1**.",
    ],
    stepCells: [[40, 36, 4], [40, 36, 4], [0, 36, 4]],
    stepStrikes: [{}, {}, { 0: [3] }],
  },
  {
    id: "swordfish",
    num: 9,
    level: "intermediate",
    title: "Swordfish",
    concept:
      "Un chiffre se répartit sur trois [[lignes]] et toutes ses places tombent dans les trois mêmes [[colonnes]] : c’est le [[Swordfish]]. C’est un X-Wing en plus grand : ces trois colonnes se partageront le chiffre sur ces lignes. Tu peux donc le [[barrer]] ailleurs dans ces colonnes.",
    question: "Le 3 dessine un Swordfish sur les lignes 1, 5 et 9. Que devient la case L3C3 ?",
    hint: "Suis le 3 sur les lignes 1, 5 et 9. Combien de colonnes différentes occupe-t-il en tout ?",
    given: {},
    notes: {
      2: [3, 5], 4: [3, 6], 40: [3, 7], 42: [3, 8], 74: [1, 3], 78: [2, 3],
      20: [3, 9],
    },
    removals: { 20: [3] },
    unit: [...COLS[2], ...COLS[4], ...COLS[6]],
    focus: [2, 4, 40, 42, 74, 78],
    target: 20,
    answer: 9,
    steps: [
      "Suis le **3** sur trois lignes. Ligne 1 : **L1C3** et **L1C5** ; ligne 5 : **L5C5** et **L5C7** ; ligne 9 : **L9C3** et **L9C7**. Il ne sort jamais des colonnes 3, 5 et 7.",
      "Ces trois colonnes se partageront les 3 de ces trois lignes : c’est un [[Swordfish]]. Aucune autre case des colonnes 3, 5 et 7 ne peut être un 3. Barre le 3 de **L3C3**.",
      "Dans la case **L3C3**, il ne reste plus que le **9**. Écris donc **9** dans **L3C3**.",
    ],
    stepCells: [[2, 4, 40, 42, 74, 78], [2, 4, 20, 40, 42, 74, 78], [20]],
    stepStrikes: [{}, { 20: [3] }, {}],
  },
  {
    id: "skyscraper",
    num: 10,
    level: "intermediate",
    title: "Skyscraper",
    concept:
      "Un chiffre forme deux [[liens forts]] sur deux [[lignes]], et ces liens partagent une même [[colonne]] : c’est le [[Skyscraper]]. Cette colonne est la base, les deux autres cases sont les toits. La base ne peut pas porter le chiffre deux fois : l’un des deux toits le porte forcément. Toute case qui [[voit]] les deux toits perd ce chiffre.",
    question: "Les deux liens forts du 5 se rejoignent sur la colonne 1. Quel chiffre va dans la case L2C6 ?",
    hint: "Le 5 n’a que deux places sur la ligne 1 et deux sur la ligne 4. Que partagent ces deux liens ?",
    given: {},
    notes: {
      0: [1, 5], 4: [2, 5], 27: [3, 5], 32: [4, 5],
      14: [5, 8],
    },
    removals: { 14: [5] },
    unit: [0, 4, 27, 32, 14],
    focus: [0, 4, 27, 32],
    target: 14,
    answer: 8,
    steps: [
      "Suis le **5** : sur la ligne 1, il n’a que **L1C1** et **L1C5** ; sur la ligne 4, il n’a que **L4C1** et **L4C6**. Les pieds L1C1 et L4C1 partagent la colonne 1 : c’est la base.",
      "La base ne peut pas porter deux 5. L’un des deux toits, **L1C5** ou **L4C6**, est donc forcément un 5.",
      "**L2C6** voit ces deux toits, par la colonne 6 et par le bloc : elle perd le 5. Barre le 5 de L2C6 : il ne reste que le **8**. Écris donc **8** dans **L2C6**.",
    ],
    stepCells: [[0, 4, 27, 32], [4, 32], [4, 14, 32]],
    stepStrikes: [{}, {}, { 14: [5] }],
  },
  {
    id: "remote-pairs",
    num: 11,
    level: "intermediate",
    title: "Remote Pairs",
    concept:
      "Plusieurs cases n’acceptent que les deux mêmes chiffres et se suivent de proche en proche : ce sont des [[Remote Pairs]]. Le long de la chaîne, les deux chiffres s’alternent, comme deux [[couleurs]]. Toute case extérieure qui [[voit]] deux maillons de couleurs opposées ne peut être ni l’un ni l’autre.",
    question: "La chaîne 1 et 2 serpente jusqu’à cerner L1C9. Quel chiffre s’y pose ?",
    hint: "Colorie la chaîne en alternance. Quelles cases L1C9 voit-elle aux deux extrémités ?",
    given: {},
    notes: {
      0: [1, 2], 4: [1, 2], 40: [1, 2], 44: [1, 2],
      8: [2, 5],
    },
    removals: { 8: [2] },
    unit: [0, 4, 40, 44, 8],
    focus: [0, 4, 40, 44],
    target: 8,
    answer: 5,
    steps: [
      "Quatre cases n’acceptent que 1 et 2 et s’enchaînent : **L1C1**, **L1C5**, **L5C5** puis **L5C9**. Colorie-les en alternance.",
      "Le 1 et le 2 s’échangent le long de la chaîne. Les extrémités **L1C1** et **L5C9** sont de couleurs opposées : l’une porte le 1, l’autre le 2.",
      "**L1C9** voit ces deux extrémités : elle ne peut être ni 1 ni 2. Barre le 2 de L1C9 : il ne reste que le **5**. Écris donc **5** dans **L1C9**.",
    ],
    stepCells: [[0, 4, 40, 44], [0, 44], [0, 8, 44]],
    stepStrikes: [{}, {}, { 8: [2] }],
  },
  {
    id: "xyz-wing",
    num: 12,
    level: "advanced",
    title: "XYZ-Wing",
    concept:
      "Le cousin du XY-Wing, avec un [[pivot]] à trois [[candidats]] : c’est le [[XYZ-Wing]]. Le pivot hésite entre x, y et z ; une pince entre x et z, l’autre entre y et z. Quel que soit le pivot, un z apparaît dans le trio, parfois dans le pivot lui-même. Tu ne barres donc le z que dans les cases qui [[voient]] les trois.",
    question: "Pivot en L5C4, pinces en L5C1 et L4C5. Quel chiffre va dans la case L5C5 ?",
    hint: "Teste les trois valeurs possibles du pivot L5C4. Dans chaque cas, où apparaît le 9 ?",
    given: {},
    notes: { 39: [2, 5, 9], 36: [2, 9], 31: [5, 9], 40: [4, 9], 41: [7, 8, 9] },
    removals: { 40: [9], 41: [9] },
    unit: [...ROWS[4], ...BOXES[4]],
    focus: [39, 36, 31],
    target: 40,
    answer: 4,
    steps: [
      "Le [[pivot]] **L5C4** hésite entre 2, 5 et 9. Sa [[pince]] **L5C1** hésite entre 2 et 9, sur la même ligne. Sa pince **L4C5** hésite entre 5 et 9, dans le même bloc.",
      "Si le pivot vaut 2, alors L5C1 vaut 9. S’il vaut 5, alors L4C5 vaut 9. S’il vaut 9, le pivot lui-même est le 9.",
      "Dans les trois cas, un 9 apparaît dans le trio. Toute case qui voit **les trois** ne peut pas être un 9. Barre le 9 de **L5C5** et de **L5C6**.",
      "Dans la case **L5C5**, il ne reste plus que le **4**. Écris donc **4** dans **L5C5**.",
    ],
    stepCells: [[39, 36, 31], [39, 36, 31], [31, 36, 39, 40, 41], [40]],
    stepStrikes: [{}, {}, { 40: [9], 41: [9] }, {}],
  },
  {
    id: "w-wing",
    num: 13,
    level: "advanced",
    title: "W-Wing",
    concept:
      "Deux cases éloignées n’acceptent que les deux mêmes chiffres a et b, sans se [[voir]]. Reliées par un [[lien fort]] sur b, elles forment un [[W-Wing]]. Le lien fort est une zone où b n’a que deux places, chacune voyant l’une des deux cases. L’une des deux cases vaut alors forcément a : [[barre]] a partout où l’on voit les deux.",
    question: "Deux paires 4 et 7 reliées par les 7 de la colonne 5. Quel chiffre va dans la case L6C2 ?",
    hint: "Dans la colonne 5, le 7 n’a que deux places. Suppose chacune vraie à tour de rôle : que deviennent L2C2 et L6C8 ?",
    given: {},
    notes: { 10: [4, 7], 52: [4, 7], 13: [3, 7], 49: [7, 9], 46: [4, 8], 16: [1, 4, 6] },
    removals: { 46: [4], 16: [4] },
    unit: [...COLS[4]],
    focus: [10, 52, 13, 49],
    target: 46,
    answer: 8,
    steps: [
      "**L2C2** et **L6C8** hésitent toutes les deux entre 4 et 7, sans se voir. Dans la **colonne 5**, le 7 n’a que deux places : **L2C5** et **L6C5**. C’est un [[lien fort]].",
      "Si L2C5 vaut 7, alors L2C2 perd son 7 et vaut **4**. Si L6C5 vaut 7, alors L6C8 perd son 7 et vaut **4**.",
      "Dans tous les cas, l’une des deux paires vaut 4 : c’est un [[W-Wing]]. Toute case qui voit les deux perd le 4. Barre le 4 de **L6C2** et de **L2C8**.",
      "Dans la case **L6C2**, il ne reste plus que le **8**. Écris donc **8** dans **L6C2**.",
    ],
    stepCells: [[10, 52, 13, 49], [10, 52, 13, 49], [10, 46, 52], [46]],
    stepStrikes: [{}, {}, { 46: [4], 16: [4] }, {}],
  },
  {
    id: "kite",
    num: 14,
    level: "advanced",
    title: "2-String Kite",
    concept:
      "Un chiffre a deux places sur une [[ligne]] et deux sur une [[colonne]], une de chaque dans le même [[bloc]] : c’est le [[2-String Kite]]. Ces deux places du bloc ne peuvent pas être vraies ensemble. L’une des deux extrémités libres porte donc le chiffre : [[barre]]-le à leur croisement.",
    question: "Le 3 forme un cerf-volant entre la ligne 2 et la colonne 7. Quel chiffre va dans la case L8C5 ?",
    hint: "Dans le bloc haut-droit, L2C9 et L3C7 peuvent-ils être tous les deux des 3 ? Déroule les conséquences.",
    given: {},
    notes: { 13: [3, 8], 17: [3, 5], 24: [2, 3], 69: [3, 4], 67: [3, 6] },
    removals: { 67: [3] },
    unit: [...ROWS[1], ...COLS[6]],
    focus: [13, 17, 24, 69],
    target: 67,
    answer: 6,
    steps: [
      "Suis le **3** : sur la ligne 2, seulement **L2C5** et **L2C9** ; sur la colonne 7, seulement **L3C7** et **L8C7**. Et **L2C9** et **L3C7** partagent le bloc haut-droit.",
      "Si L2C5 n’est pas un 3, alors L2C9 vaut 3. L3C7 ne peut plus l’être, même bloc, donc **L8C7** vaut 3. Ainsi L2C5 ou L8C7 est forcément un 3.",
      "**L8C5** voit ces deux extrémités : L2C5 par la colonne 5, L8C7 par la ligne 8. Elle ne peut pas être un 3. Barre le 3 de **L8C5**.",
      "Dans la case **L8C5**, il ne reste plus que le **6**. Écris donc **6** dans **L8C5**.",
    ],
    stepCells: [[13, 17, 24, 69], [13, 17, 24, 69], [13, 67, 69], [67]],
    stepStrikes: [{}, {}, { 67: [3] }, {}],
  },
  {
    id: "empty-rectangle",
    num: 15,
    level: "advanced",
    title: "Empty Rectangle",
    concept:
      "Dans un [[bloc]], tous les [[candidats]] d’un chiffre tiennent dans une ligne plus une colonne, et le reste est vide : c’est l’[[Empty Rectangle]]. Combiné à un [[lien fort]] ailleurs, il barre le chiffre à un croisement précis. Si la case visée était vraie, le bloc n’aurait plus aucune place pour ce chiffre.",
    question: "Les 6 du bloc central tiennent dans la ligne 5 et la colonne 4. Quel chiffre va dans la case L5C8 ?",
    hint: "Suppose L5C8 égal à 6, et suis les conséquences. Que devient le lien fort de la ligne 8, puis le bloc central ?",
    given: {},
    notes: { 30: [6, 8], 39: [5, 6], 40: [2, 6], 41: [6, 7], 48: [3, 6], 66: [1, 6], 70: [4, 6], 43: [6, 9] },
    removals: { 43: [6] },
    unit: [...BOXES[4], ...ROWS[7]],
    focus: [66, 70],
    target: 43,
    answer: 9,
    steps: [
      "Dans le **bloc central**, le 6 ne se trouve que dans la **ligne 5** et la **colonne 4** : L4C4, L5C4, L5C5, L5C6 et L6C4. Le reste du rectangle est vide.",
      "Autre indice : dans la **ligne 8**, le 6 n’a que deux places, **L8C4** et **L8C8**. C’est un [[lien fort]], et L8C4 est justement en colonne 4.",
      "Suppose **L5C8** égal à 6 : la ligne 5 et la colonne 8 se vident, donc L8C8 perd le 6 et **L8C4** vaut 6. La colonne 4 se vide aussi, et le bloc central n’a plus aucune place pour son 6. Contradiction : barre le 6 de L5C8.",
      "Dans la case **L5C8**, il ne reste plus que le **9**. Écris donc **9** dans **L5C8**.",
    ],
    stepCells: [[30, 39, 40, 41, 48], [66, 70], [43, 66, 70], [43]],
    stepStrikes: [{}, {}, { 43: [6] }, {}],
  },
  {
    id: "coloring",
    num: 16,
    level: "advanced",
    title: "Coloriage",
    concept:
      "Suis un seul chiffre à travers ses [[liens forts]] en coloriant les cases en deux [[couleurs]] alternées : c’est le [[Coloriage]]. Une couleur est vraie partout, l’autre fausse partout. Si deux cases de la même couleur se retrouvent dans une même zone, cette couleur est fausse partout, et l’autre est vraie partout.",
    question: "Colorie les 5 de la chaîne. Quel chiffre va dans la case L8C3 ?",
    hint: "Alterne ➊ et ➋ le long des liens. Deux cases ➊ ne partagent-elles pas le même bloc ?",
    given: {},
    // Le 5 de L1C2 garde 3 places au 5 dans le bloc haut-gauche : le bloc n'est
    // pas un lien conjugué de la chaîne, c'est la zone où la couleur ➊ « wrap ».
    notes: { 1: [2, 5], 11: [5, 8], 65: [3, 5], 69: [5, 6], 24: [2, 5], 18: [5, 9] },
    removals: { 11: [5], 69: [5], 18: [5] },
    unit: [...COLS[2], ...ROWS[7], ...COLS[6], ...ROWS[2]],
    focus: [11, 65, 69, 24, 18],
    target: 65,
    answer: 5,
    steps: [
      "Suis le **5** de [[lien fort]] en lien fort. Colonne 3 : L2C3 et L8C3, puis ligne 8 : L8C3 et L8C7. Colonne 7 : L8C7 et L3C7, puis ligne 3 : L3C7 et L3C1.",
      "Colorie en alternance : L2C3 ➊, L8C3 ➋, L8C7 ➊, L3C7 ➋, L3C1 ➊. Une couleur est entièrement vraie, l’autre entièrement fausse.",
      "Or **L2C3** ➊ et **L3C1** ➊ partagent le bloc haut-gauche : la couleur ➊ mettrait deux 5 dans le même bloc. Elle est donc fausse partout. Barre le 5 de L2C3, de L8C7 et de L3C1.",
      "La couleur ➋ est donc vraie. Écris **5** dans **L8C3**, et aussi dans L3C7.",
    ],
    stepCells: [[11, 65, 69, 24, 18], [11, 65, 69, 24, 18], [11, 18, 69], [24, 65]],
    stepStrikes: [{}, {}, { 11: [5], 69: [5], 18: [5] }, {}],
  },
  {
    id: "sue-de-coq",
    num: 17,
    level: "advanced",
    title: "Sue de Coq",
    concept:
      "Un comptage serré à cheval entre une [[ligne]] et un [[bloc]] : c’est le [[Sue de Coq]]. Deux cases d’intersection puisent dans un pool de quatre chiffres. Une case de la ligne et une case du bloc, à deux [[candidats]] chacune, se partagent ce pool sans se chevaucher. Chaque chiffre du pool a alors sa place réservée : tu nettoies tout autour.",
    question: "Quatre chiffres 1, 2, 5 et 7 pour quatre cases. Quel chiffre va dans la case L1C5 ?",
    hint: "L1C8 prend un chiffre parmi 1 et 2, L3C1 un chiffre parmi 5 et 7. Que reste-t-il pour les deux cases d’intersection L1C1 et L1C2 ?",
    given: {},
    notes: { 0: [1, 2, 5], 1: [2, 5, 7], 7: [1, 2], 18: [5, 7], 4: [1, 2, 4], 10: [5, 8, 9] },
    removals: { 4: [1, 2], 10: [5] },
    unit: [...ROWS[0], ...BOXES[0]],
    focus: [0, 1, 7, 18],
    target: 4,
    answer: 4,
    steps: [
      "Le pool est 1, 2, 5 et 7. À l’intersection de la ligne 1 et du bloc, **L1C1** hésite entre 1, 2 et 5, et **L1C2** entre 2, 5 et 7. Dans la ligne, **L1C8** hésite entre 1 et 2 ; dans le bloc, **L3C1** entre 5 et 7.",
      "L1C8 prend un chiffre parmi 1 et 2 : l’intersection, qui la voit, ne garde que l’autre. L3C1 prend un chiffre parmi 5 et 7 : même chose. L1C1 et L1C2 contiennent donc exactement un chiffre parmi 1 et 2, et un parmi 5 et 7.",
      "Bilan : le 1 et le 2 sont casés dans la ligne 1, entre L1C8 et l’intersection. Barre le 1 et le 2 de **L1C5**. Le 5 et le 7 sont casés dans le bloc : barre le 5 de **L2C2**.",
      "Dans la case **L1C5**, il ne reste plus que le **4**. Écris donc **4** dans **L1C5**.",
    ],
    stepCells: [[0, 1, 7, 18], [0, 1, 7, 18], [4, 10], [4]],
    stepStrikes: [{}, {}, { 4: [1, 2], 10: [5] }, {}],
  },
];

/* Traductions EN (lessonsEn.js) attachées à chaque leçon : L.en est lu par
   coachCopy (conceptSentence) et par lessonText. Les champs positionnels
   restent uniques aux deux langues. */
for (const L of LESSONS) L.en = LESSONS_EN[L.id];

/* Les champs texte d'une leçon dans la langue demandée — repli FR champ par
   champ si une traduction manquait. */
export function lessonText(L, lang = "fr") {
  if (lang !== "en" || !L.en) {
    return { title: L.title, concept: L.concept, question: L.question, hint: L.hint, steps: L.steps };
  }
  return {
    title: L.en.title || L.title,
    concept: L.en.concept || L.concept,
    question: L.en.question || L.question,
    hint: L.en.hint || L.hint,
    steps: Array.isArray(L.en.steps) && L.en.steps.length ? L.en.steps : L.steps,
  };
}
